[env]
name = "email_gateway"
token_secret = "secretpass"
hosts = "127.0.0.1:88,domain-swapper.myridia.com"
token_fake ="ABC1234567890"
token_valid="600"
email_send_from="smtp@foo.com"
email_send_to="smtp@foo.com"
name_send_to = "Sender"
smtp_host="foo.com"
smtp_user="api@foo.com"
smtp_pass="barbar"
smtp_port="25"
random_max="1000"
time_passed="30"